version: "3"
services:
  web:
    image: hpci/yprov:latest
    restart: on-failure
    depends_on:
      - db
    links: 
      - db
    networks:
      - yprov_net
    ports:
      - "3000:3000"
    environment:
      USER: neo4j
      PASSWORD: password
      ADDRESS: db:7687
    volumes:
      - yprov_data:/app/conf

  db:
    image: "neo4j:enterprise"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: eval 
      NEO4J_PLUGINS: '["graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - yprov_net

  test:
    image: hpci/yprov-sqa:1.4 
    depends_on:
      - web
    networks:
      - yprov_net

volumes:
  neo4j_data:
  neo4j_logs:
  yprov_data:

networks:
  yprov_net:
