version: '3.7'

services:
  db:
    image: neo4j:enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - yprov_net

  web:
    image: hpci/yprov:latest
    ports:
      - "3000:3000"
    environment:
      - USER=neo4j
      - PASSWORD=password
    volumes:
      - yprov_data:/app/conf
    networks:
      - yprov_net

volumes:
  neo4j_data:
  neo4j_logs:
  yprov_data:

networks:
  yprov_net:
    driver: bridge
