version: "3"
services:
  web:
    build: .
    restart: on-failure
    depends_on:
      - db
    links: 
      - db
    networks:
      - yprov_net
    ports:
      - "3000:3000"
    environment:
      USER: neo4j
      PASSWORD: password
      ADDRESS: db:7687
    volumes:
      - yprov_data:/app/conf

  db:
    image: "neo4j:enterprise"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: eval 
      NEO4J_PLUGINS: '["graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - yprov_net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://db:7474"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  neo4j_data:
  neo4j_logs:
  yprov_data:

networks:
  yprov_net: