version: "3"
services:
  web:
    build: .
    restart: on-failure
    depends_on:
      - db
    links: 
      - db
    ports:
      - "3000:3000"

  db:
    image: "neo4j:enterprise"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: eval 
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7474"]
        interval: 30s
        timeout: 10s
        retries: 5


