openapi: 3.0.0
info:
  title: yProv Auth
  description: yProv Authorization API
  version: 1.0.0
servers:
  - url: http://{address}:{port}/api/v0/auth
    variables:
      address:
        default: 'localhost'
      port:
        default: '3000'
    description: yProv Authorization API

paths:
  /register:
    post:
      summary: Register to the service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: "myUsername"
                password:
                  type: string
                  example: "myPassword"
      responses:
        '201':
          description: User registered
        '400':
          description: Data not valid or username already available
        '401':
          description: Registration failed
  /login:
    post:
      summary: Log in to the service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: "myUsername"
                password:
                  type: string
                  example: "myPassword"
      responses:
        '200':
          description: Return jwt token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Bearer token
        '400':
          description: Data not valid
        '401':
          description: User not registered