openapi: 3.0.0
info:
  title: yProv Documents
  description: yProv Documents API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v0/documents
    description: yProv Documents
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /:
    get:
      summary: Return all documents
      security: []
      description: Does not require authentication
      responses:
        '200':
          description: List of documents is returned
  /{doc_id}:
    parameters:
      - in: path
        name: doc_id
        required: true
        schema:
          type: string
          description: Name of document, minimum three characters
          example: "pta"
    get:
      summary: Return specified document
      security: []
      description: Does not require authentication
      responses:
        '200':
          description: Return content of document
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Document not found
    put:
      summary: Create new document
      requestBody:
        description: |
          Structure of new document.
          You can provide JSON directly.
          You can submit a JSON file using tools like curl with the `-d @filename.json` option.
          If providing JSON directly, use the `application/json` content type.
          If submitting a file, ensure it contains valid JSON data.
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Document uploaded
        '400':
          description: Document not valid
    delete:
      summary: Delete document
      responses:
        '200':
          description: Document deleted
        '403':
          description: User does not have permission to operate on this document
        '404':
          description: Document not found
        '500':
          description: Document error
  /{doc_id}/permissions:
    parameters:
      - in: path
        name: doc_id
        required: true
        schema:
          type: string
          description: ID of the document to modify permissions for, minimum three characters
          example: "pta"
    put:
      summary: Add or update user permissions for a document
      requestBody:
        description: Specifies the user and their permission level
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                {doc_id}:
                  type: string
                  example: "second_user"
                  description: User ID to grant permissions to, different from the current user
                level:
                  type: string
                  example: "r"
                  enum: ["r", "w"]
                  description: |
                    Permission level to grant.
                    - "r": Read
                    - "w": Write
      responses:
        '201':
          description: Successfully added access to the document
        '400':
          description: Data not valid
        '403':
          description: Permission issue or user not registered
        '404':
          description: Document not found
  /{doc_id}/subgraph:
    parameters:
    - in: path
      name: doc_id
      required: true
      schema:
        type: string
        description: Name of document, mininum three characters
    - in: query
      name: id
      required: true
      schema:
        type: string
        description: Name of element (entity, agent, activity)
        example: "ophidia:http://127.0.0.1/ophidia/66/7191"
    get:
      summary: Get subgraph from document
      security: []
      description: Does not require authentication
      responses:
        '200':
          description: Successfully extracted sub-graph
        '404':
          description: ID is missing or document is not found
        '500':
          description: Database error