web:
  name: web
  ports:
    name: "3000"
    port: 3000
    targetPort: 3000
  service: web
  image: hpci/yprov-im:latest

db:
  service: db
  name: db
  image: neo4j:enterprise
  ports:
    port1:
      name: port7474
      port: 7474
      targetPort: 7474
    port2:
      name: port7687
      port: 7687
      targetPort: 7687
  spec:
    replicas: 1
  env:
    auth:
      name: NEO4J_AUTH
      value: neo4j/password
    license:
      name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: eval
    plugins:
      name: NEO4J_PLUGINS
      value: '["graph-data-science"]'
  config:
    dbms.security.procedures.unrestricted: "gds.*" # added following "https://neo4j.com/docs/operations-manual/current/kubernetes/plugins/#_install_gds_community_edition_ce"

storages:
  neo4j:
    data:
      service: "neo4j-data"
      name: "neo4j-data"
      accessMode: ReadWriteOnce
      resources:
        requirements:
          storage: 100Mi
    logs:
      service: "neo4j-logs"
      name: "neo4j-logs"
      accessMode: ReadWriteOnce
      resources:
        requirements:
          storage: 100Mi
  yprov:
    service: "yprov-data"
    name: "yprov-data"
    accessMode: ReadWriteMany
    resources:
      requirements:
        storage: 200Mi