apiVersion: v1
kind: Pod
metadata:
  labels:
    network/yprov-default: "true"
    service: {{ .Values.web.service }}
  name: {{ .Values.web.name }}
spec:
  containers:
    - image: {{ .Values.web.image }}
      name: {{ .Values.web.name }}
      ports:
        - containerPort: {{ .Values.web.ports.port }}
          hostPort: {{ .Values.web.ports.port }}
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
