apiVersion: v1
kind: Pod
metadata:
  labels:
    network/yprov-default: "true"
    service: {{ .Values.web.service }}
  name: {{ .Values.web.name }}
spec:
  containers:
    - image: {{ .Values.web.image }}
      name: {{ .Values.web.name }}
      ports:
        - containerPort: {{ .Values.web.ports.port }}
          hostPort: {{ .Values.web.ports.port }}
          protocol: TCP
      resources: {}
      volumeMounts:
        - mountPath: /app/conf
          name: {{ .Values.storages.yprov.name }}
  restartPolicy: OnFailure
  volumes:
    - name: {{ .Values.storages.yprov.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.storages.yprov.name }}
status: {}
