apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: {{ .Values.storages.yprov.service }}
  name: {{ .Values.storages.yprov.name }}
spec:
  accessModes:
    - {{ .Values.storages.yprov.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storages.yprov.resources.requirements.storage }}
status: {}
