apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.db.service }}
  name: {{ .Values.db.name }}
spec:
  ports:
    - port: {{ .Values.db.ports.port1.port }}
      targetPort: {{ .Values.db.ports.port1.targetPort }}
      name: {{ .Values.db.ports.port1.name }}
      nodePort: {{ .Values.db.ports.port1.port }}
    - port: {{ .Values.db.ports.port2.port }}
      targetPort: {{ .Values.db.ports.port2.targetPort }}
      name: {{ .Values.db.ports.port2.name }}
      nodePort: {{ .Values.db.ports.port2.port }}
  selector:
    service: {{ .Values.db.service }}
  type: NodePort
status:
  loadBalancer: {}
