apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  ports:
    - port: {{ .Values.web.ports.port }}
      targetPort: {{ .Values.web.ports.targetPort }}
      name: {{ .Values.web.ports.name }}
  selector:
    service: {{ .Values.web.service }}
  type: NodePort
status:
  loadBalancer: {}