web:
  name: web
  service: web
  image: hpci/yprov:latest
  ports:
    name: port3000
    port: 3000
    targetPort: 3000
  spec:
    replicas: 1
  env:
    user:
      name: USER
      value: neo4j
    password:
      name: PASSWORD
      value: password

db:
  service: db
  name: db
  image: neo4j:enterprise
  ports:
    port1:
      name: port7474
      port: 7474
      targetPort: 7474
    port2:
      name: port7687
      port: 7687
      targetPort: 7687
  spec:
    replicas: 1
  env:
    auth:
      name: NEO4J_AUTH
      value: neo4j/password
    license:
      name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: eval
    apoc_export:
      name: NEO4J_apoc_export_file_enabled
      value: true 
    apoc_import:
       name: NEO4J_apoc_import_file_enabled
       value: true  
    apoc_import_config:
      name: NEO4J_apoc_import_file_use__neo4j__config
      value: true
    plugins:
      name: NEO4J_PLUGINS
      value: |
        '["apoc", "graph-data-science"]'
  config:
    dbms.security.procedures.unrestricted: "gds.*"

storages:
  neo4j:
    data:
      service: "neo4j-data"
      name: "neo4j-data"
      accessMode: ReadWriteMany
      resources:
        requirements:
          storage: 100Mi
    logs:
      service: "neo4j-logs"
      name: "neo4j-logs"
      accessMode: ReadWriteMany
      resources:
        requirements:
          storage: 100Mi
  yprov:
    service: "yprov-data"
    name: "yprov-data"
    accessMode: ReadWriteMany
    resources:
      requirements:
        storage: 200Mi